filename: app
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local_database
    username: local_user
    password: local_password

  kafka:
    bootstrap-servers: kafka:9092

socnet:
  vk:
    appId: 123
    secretKey: secretKey
